# Generated by Django 2.2.6 on 2019-10-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_auto_20191017_1637'),
        ('association', '0011_auto_20191017_1709'),
    ]

    operations = [
    ]
