# Generated by Django 2.2.6 on 2019-10-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0017_auto_20191022_1343'),
        ('association', '0013_auto_20191022_1259'),
    ]

    operations = [
    ]
