# Generated by Django 2.2.6 on 2019-10-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0020_auto_20191022_1710'),
        ('association', '0018_merge_20191022_1702'),
    ]

    operations = [
    ]
