# Generated by Django 2.2.6 on 2019-12-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0024_auto_20191206_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='athletic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaa.AAA'),
        ),
        migrations.AlterField(
            model_name='association',
            name='date_entry',
            field=models.DateField(auto_now_add=True),
        ),
    ]
