# Generated by Django 2.2.6 on 2019-10-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_auto_20191017_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='director',
            name='athletic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaa.AAA'),
        ),
    ]
