# Generated by Django 2.2.6 on 2019-10-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0008_auto_20191018_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='athletic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaa.AAA'),
        ),
    ]
