# Generated by Django 2.2.6 on 2019-10-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0008_auto_20191022_1259'),
        ('director', '0012_auto_20191022_1343'),
    ]

    operations = [
    ]
