# Generated by Django 2.2.6 on 2019-10-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0013_merge_20191022_1702'),
        ('director', '0015_auto_20191022_1710'),
    ]

    operations = [
    ]
