# Generated by Django 2.2.6 on 2019-10-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20191017_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='athletic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aaa.AAA'),
        ),
    ]
