# Generated by Django 2.2.6 on 2019-10-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_auto_20191018_1347'),
        ('partner', '0012_merge_20191018_1318'),
    ]

    operations = [
    ]
