# Generated by Django 3.1.12 on 2021-07-07 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Anônimo', max_length=255, verbose_name='Nome completo')),
                ('course_name', models.CharField(default='', max_length=255, verbose_name='Nome do curso')),
                ('cpf', models.CharField(default='', max_length=14, verbose_name='CPF')),
                ('date_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento')),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
