# Generated by Django 2.2.6 on 2019-10-17 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191017_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
    ]
