# Generated by Django 2.2.6 on 2019-10-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191017_1505'),
        ('core', '0003_auto_20191017_1504'),
    ]

    operations = [
    ]
