# Generated by Django 2.2.6 on 2019-10-17 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191017_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do curso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Anônimo', max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
