# Generated by Django 2.2.6 on 2019-10-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20191017_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
    ]
