# Generated by Django 2.2.6 on 2019-10-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191017_1528'),
        ('core', '0005_auto_20191017_1518'),
    ]

    operations = [
    ]
