# Generated by Django 3.1.12 on 2021-07-07 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da AAA')),
                ('created_data', models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('logo', models.ImageField(upload_to='')),
                ('value_association', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da associação')),
            ],
            options={
                'verbose_name': 'AAA',
                'verbose_name_plural': 'AAAs',
                'ordering': ['name'],
            },
        ),
    ]
