# Generated by Django 2.2.6 on 2019-10-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
