# Generated by Django 2.2.6 on 2019-10-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0002_auto_20191017_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aaa',
            options={'ordering': ['name'], 'verbose_name': 'aaa', 'verbose_name_plural': 'aaa'},
        ),
    ]
