# Generated by Django 2.2.6 on 2019-10-17 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0005_auto_20191017_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='created_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
    ]
