# Generated by Django 2.2.6 on 2019-10-17 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0008_auto_20191017_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaa',
            name='created_data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
    ]
