# Generated by Django 2.2.6 on 2019-10-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20191022_1343'),
        ('notice', '0004_auto_20191022_1259'),
    ]

    operations = [
    ]
