# Generated by Django 2.2.6 on 2019-10-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_merge_20191022_1701'),
        ('notice', '0008_auto_20191022_1710'),
    ]

    operations = [
    ]
